import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateBrandTable1725965919557 implements MigrationInterface {
    name = 'CreateBrandTable1725965919557'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "company_user" DROP CONSTRAINT "fk_company_user_company_id"`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "fk_company_company_type_id"`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "fk_company_liquidate_unit_id"`);
        await queryRunner.query(`CREATE TABLE "brands" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "category_id" character varying NOT NULL, "category_name" character varying NOT NULL, "sub_category_id" character varying NOT NULL, "sub_category_name" character varying NOT NULL, "image" character varying, "status" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e1bffaa53eebf883232cb6dfb86" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "pollen_pass_id" integer NOT NULL, "first_name" character varying(50) NOT NULL, "last_name" character varying(50) NOT NULL, "country_code" integer NOT NULL, "phone_no" integer NOT NULL, "phone_verified" boolean NOT NULL DEFAULT false, "email" character varying(200) NOT NULL, "auth_ref_id" character varying NOT NULL, "auth_id" uuid NOT NULL, "channel" character varying NOT NULL, "status" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "states" ("id" integer NOT NULL, "name" character varying(255) NOT NULL, "country_id" integer NOT NULL, "country_code" character(2) NOT NULL, "fips_code" character varying(255), "iso2" character varying(255), "type" character varying(191), "latitude" numeric(10,8), "longitude" numeric(11,8), "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "flag" boolean NOT NULL DEFAULT true, "wikidataid" character varying(255), CONSTRAINT "PK_09ab30ca0975c02656483265f4f" PRIMARY KEY ("id")); COMMENT ON COLUMN "states"."wikidataid" IS 'Rapid API GeoDB Cities'`);
        await queryRunner.query(`CREATE INDEX "idx_16410_country_region" ON "states" ("country_id") `);
        await queryRunner.query(`CREATE TABLE "regions" ("id" integer NOT NULL, "name" character varying(100) NOT NULL, "translations" text, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "flag" boolean NOT NULL DEFAULT true, "wikidataid" character varying(255), CONSTRAINT "PK_4fcd12ed6a046276e2deb08801c" PRIMARY KEY ("id")); COMMENT ON COLUMN "regions"."wikidataid" IS 'Rapid API GeoDB Cities'`);
        await queryRunner.query(`CREATE TABLE "subregions" ("id" integer NOT NULL, "name" character varying(100) NOT NULL, "translations" text, "region_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "flag" boolean NOT NULL DEFAULT true, "wikidataid" character varying(255), CONSTRAINT "PK_46f1f54bc9fdaedea223127924d" PRIMARY KEY ("id")); COMMENT ON COLUMN "subregions"."wikidataid" IS 'Rapid API GeoDB Cities'`);
        await queryRunner.query(`CREATE INDEX "idx_16418_subregion_continent" ON "subregions" ("region_id") `);
        await queryRunner.query(`CREATE TABLE "city" ("id" integer NOT NULL, "name" character varying NOT NULL, "country_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying NOT NULL, CONSTRAINT "PK_b222f51ce26f7e5ca86944a6739" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "company_user" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" DROP CONSTRAINT "liquidate_unit_pkey"`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" ADD "id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" ADD CONSTRAINT "PK_7f6c5151619981eb09427467c36" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_user" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "company_user" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "company_user" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_user" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "company_user" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "company_user" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "company_user" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "company_type" DROP CONSTRAINT "company_type_pkey"`);
        await queryRunner.query(`ALTER TABLE "company_type" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "company_type" ADD "id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_type" ADD CONSTRAINT "PK_b21e9ab8361b2fcc85e6c4f4fa7" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "company_type" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "company_type" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_type" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "company_type" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_type" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "company_type" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "company_pkey"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "account_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "account_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "uq_company_name"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "company_type_id"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "company_type_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "country_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "country_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "country_name"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "country_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "liquidate_unit_id"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "liquidate_unit_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "liquidate_unit_name"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "liquidate_unit_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "iso3"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "iso3" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "phone_code"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "phone_code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "states" ADD CONSTRAINT "country_region_final" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "subregions" ADD CONSTRAINT "subregion_continent_final" FOREIGN KEY ("region_id") REFERENCES "regions"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subregions" DROP CONSTRAINT "subregion_continent_final"`);
        await queryRunner.query(`ALTER TABLE "states" DROP CONSTRAINT "country_region_final"`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "status" character varying(25) NOT NULL DEFAULT 'NA'`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "phone_code"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "phone_code" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "iso3"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "iso3" character varying(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "country" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "country" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "status" character varying(25) NOT NULL DEFAULT 'NA'`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "liquidate_unit_name"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "liquidate_unit_name" character varying(100) DEFAULT 'NA'`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "liquidate_unit_id"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "liquidate_unit_id" smallint DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "country_name"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "country_name" character varying(100) NOT NULL DEFAULT 'NA'`);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "country_id" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "country_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "company_type_id"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "company_type_id" smallint DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "uq_company_name" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "account_id" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "company" ALTER COLUMN "account_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "company_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "company_type" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "company_type" ADD "status" character varying(25) NOT NULL DEFAULT 'NA'`);
        await queryRunner.query(`ALTER TABLE "company_type" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "company_type" ADD "description" character varying(250) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_type" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "company_type" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_type" DROP CONSTRAINT "PK_b21e9ab8361b2fcc85e6c4f4fa7"`);
        await queryRunner.query(`ALTER TABLE "company_type" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "company_type" ADD "id" smallint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_type" ADD CONSTRAINT "company_type_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "company_user" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "company_user" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "company_user" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "company_user" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "company_user" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "company_user" ADD "status" character varying(25) NOT NULL DEFAULT 'NA'`);
        await queryRunner.query(`ALTER TABLE "company_user" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" ADD "status" character varying(25) NOT NULL DEFAULT 'NA'`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" ADD "description" character varying(250) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" DROP CONSTRAINT "PK_7f6c5151619981eb09427467c36"`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" ADD "id" smallint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "liquidate_unit" ADD CONSTRAINT "liquidate_unit_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "company" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "company_user" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`DROP TABLE "city"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16418_subregion_continent"`);
        await queryRunner.query(`DROP TABLE "subregions"`);
        await queryRunner.query(`DROP TABLE "regions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16410_country_region"`);
        await queryRunner.query(`DROP TABLE "states"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "brands"`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "fk_company_liquidate_unit_id" FOREIGN KEY ("liquidate_unit_id") REFERENCES "liquidate_unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "fk_company_company_type_id" FOREIGN KEY ("company_type_id") REFERENCES "company_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_user" ADD CONSTRAINT "fk_company_user_company_id" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
